### ISSUE TITLE
Doesn't work since last update

### ISSUE THREAD

**Issue by Nojipiz** [jetli/create-yew-app#21]
Creating the project with `npx create-yew-app my-app` works fine but `npm start` uses parcel to build stuff and don't start the app in the browser.
Here is the console of the browser
```
Uncaught TypeError: Cannot read properties of undefined (reading 'memory')
    at parcelRequire.../node_modules/parcel-plugin-wasm.rs/wasm-loader.js.fs (wasm-loader.js:859:1)
    at newRequire (static.77de5100.js:47:24)
    at localRequire (static.77de5100.js:53:14)
    at parcelRequire.0 (wasm-loader.js:904:1)
    at newRequire (static.77de5100.js:47:24)
    at static.77de5100.js:81:7
    at static.77de5100.js:120:3
```

**Comment by jetli** [comment]
seems there's something wrong with latest version of wasm-bindgen, can you try to force to use previous version like this in your Cargo.toml
```toml
wasm-bindgen = "=0.2.80"
```
and make sure you have installed previous version of wasm-bindgen-cli
```bash
cargo install wasm-bindgen-cli --version 0.2.80
```

**Comment by Nojipiz** [comment]
Should i leave this issue open in case someone has the same problem?

**Comment by jetli** [comment]
Yes, keep this open, until wasm-bindgen is fixed or any better way to resolve this. I may open an issue to wasm-bindgen

**Comment by Nojipiz** [comment]
Hello again!
I have check the last version of wasm-bindgen and its working again :)

`wasm-bindgen = "0.2.83"`

Just don't use the version `=0.2.80` ;)
