### ISSUE TITLE
Fails to find cache if folder path has a space in it

### ISSUE THREAD

**Issue by lord-ne** [jetli/create-yew-app#23]
Compiling gives the message: 
```
×  Error writing to cache: ENOENT: no such file or directory, stat 'C:\Users\Noam\Desktop\Programs\Research2022\contact-picker\target\wasm32-unknown-unknown\debug\yew_app.wasm'
```

Note that it is looking in the `Research2022` folder. However, the folder that the app is inside of is *actually* named `Research 2022` with a space

**Comment by jetli** [comment]
upgrade to use trunk,  `npx create-yew-app@0.2.0 my-app`
