### ISSUE TITLE
How to let parcel load image referenced from inside .rs

### ISSUE THREAD

**Issue by wtho** [jetli/create-yew-app#5]
Hey! Thanks for this starter!

I reference my image in `html! { <img src="logo.png"></img> }`, but parcel does not load it.
Is there some way to do so?
Is this the right place to ask this?

**Comment by wtho** [comment]
My current workaround is:
* build app once and check hash of image
* reference image with hash in rust html:  
  `html! { <img src="logo.b1252105.png"></img> }`

**Comment by Nojipiz** [comment]
2 years later, is still missing the way of create a "resources" folder, so i just convert the image to base64, and later set the: `html!{<img src="base64codehere"/>}`

**Comment by jetli** [comment]
upgrade to use trunk,  `npx create-yew-app@0.2.0 my-app`
