### ISSUE TITLE
web_logger depends on stdweb

### ISSUE THREAD

**Issue by Stigjb** [jetli/create-yew-app#8]
To avoid a `stdweb` dependency in a `web-sys` project, the logging crate can be replaced, e.g. with [`wasm-logger`](https://crates.io/crates/wasm-logger)

**Comment by jetli** [comment]
@Stigjb  web_logger is maintained by the yew team, and I just open an issue to support web-sys by default: https://github.com/yewstack/web_logger/issues/5, let's see if yew team can improve this since the yew main repo has switched to web-sys by default.

**Comment by jetli** [comment]
Switched to wasm-logger for now
